# Generated by Django 4.1.2 on 2023-01-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manzil',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
